#ifndef IDENTITY_RECORD_H
#define IDENTITY_RECORD_H

#define ROADRUNNER_IDENTITY_FLASH_OFFSET 0x1FF000u
#define ROADRUNNER_IDENTITY_SECTOR_SIZE 0x1000u
#define ROADRUNNER_APPLICATION_FLASH_SIZE 0x1FF000u

#endif
